<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Gyeori Won" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="gyeori-won-gw6936" class="section level5">
<h5>Gyeori Won (gw6936)</h5>
<P style="page-break-before: always">
<div style="page-break-after: always;"></div>
</div>
<div id="introduction" class="section level3">
<h3>Introduction</h3>
<p>The dataset chosen for this project is <code>stroke</code> and this dataset shows 11 clinical features for predicting stroke events. There are originally 5110 observations with 12 attributes: id, gender, age, hypertension, heart disease, ever married, work type, residence type, avg glucose level, bmi, smoking status, and stroke. However, there were some rows without variables, and these rows were dropped to result in a final dataset with 4909 observations. The id is a unique identifier of each patient, age is a numeric variable, and gender is a categorical variable that tells whether the patient is a male or female. Hypertension, heart disease, and stroke are numeric binary variables, with 1 meaning the patient has a hypertension, heart disease, and stroke, and 0 meaning he/she does not. Ever married is a categorical variable that shows the marriage status of each patient. Work type is a categorical variable which shows the occupation status of each patient as being children, government worker, never worked, self-employed, or private. The residence type is another categorical variable that shows whether the patient is from an urban or rural residence. The avg glucose level and bmi are numerical variables that give insight to the average glucose level and the body mass index of each patient. Smoking status is a categorical variable that is distinguished by formerly smoked, never smoked, smokes, or unknown, in which unknown means that the information is unavailable for that patient.</p>
<pre class="r"><code>library(tidyverse)
library(cluster)
library(ggplot2)
stroke &lt;- read_csv(&quot;stroke.csv&quot;)
# drop rows without data
stroke &lt;- stroke %&gt;% drop_na()
head(stroke)</code></pre>
<pre><code>## # A tibble: 6 x 12
## id gender age hypertension `heart disease` `ever
married` `work type` `residence type`
## &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;
## 1 9046 Male 67 0 1 Yes Private Urban
## 2 31112 Male 80 0 1 Yes Private Rural
## 3 60182 Female 49 0 0 Yes Private Urban
## 4 1665 Female 79 1 0 Yes Self-emplo… Rural
## 5 56669 Male 81 0 0 Yes Private Urban
## 6 53882 Male 74 1 1 Yes Private Rural
## # … with 4 more variables: `avg glucose level` &lt;dbl&gt;,
bmi &lt;dbl&gt;, `smoking status` &lt;chr&gt;,
## # stroke &lt;dbl&gt;</code></pre>
</div>
<div id="manova-test" class="section level3">
<h3>1 - MANOVA test</h3>
<pre class="r"><code>library(rstatix)
group &lt;- stroke$`work type`
DVs &lt;- stroke %&gt;% select(age, `avg glucose level`, bmi)

# Test multivariate normality for each group (null:
# assumption met)
sapply(split(DVs, group), mshapiro_test)</code></pre>
<pre><code>## children Govt_job Never_worked Private Self-employed
## statistic 0.8931384 0.9460166 0.8696865 0.911635
0.9631404
## p.value 3.603958e-21 2.210924e-14 0.007723588
1.157509e-37 4.63647e-13</code></pre>
<pre class="r"><code># Optionally view covariance matrices for each group
lapply(split(DVs, group), cov)</code></pre>
<pre><code>## $children
##                         age avg glucose level       bmi
## age               20.577935          4.526234  7.999032
## avg glucose level  4.526234        663.215447  8.884161
## bmi                7.999032          8.884161 20.617404
## 
## $Govt_job
##                          age avg glucose level       bmi
## age               234.091746          167.1962  6.217531
## avg glucose level 167.196240         2247.7277 40.703897
## bmi                 6.217531           40.7039 47.877748
## 
## $Never_worked
##                          age avg glucose level        bmi
## age                5.4891775         -4.722424  0.6484848
## avg glucose level -4.7224242        823.525364 -5.3423203
## bmi                0.6484848         -5.342320 55.3797403
## 
## $Private
##                         age avg glucose level      bmi
## age               337.27267         196.37502 12.44891
## avg glucose level 196.37502        2005.18816 47.72675
## bmi                12.44891          47.72675 57.49678
## 
## $`Self-employed`
##                          age avg glucose level       bmi
## age               289.120864         149.35321 -6.395515
## avg glucose level 149.353211        2644.18824 72.908243
## bmi                -6.395515          72.90824 44.725182</code></pre>
<pre class="r"><code># MANOVA
man1 &lt;- manova(cbind(age, `avg glucose level`, bmi) ~ `work type`, 
    data = stroke)
summary(man1)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## `work type` 4 0.54294 270.91 12 14712 &lt; 2.2e-16 ***
## Residuals 4904
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code># ANOVA
summary.aov(man1)</code></pre>
<pre><code>## Response age :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## `work type` 4 1164201 291050 1071 &lt; 2.2e-16 ***
## Residuals 4904 1332662 272
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response avg glucose level :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## `work type` 4 129397 32349 16.6 1.609e-13 ***
## Residuals 4904 9556650 1949
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response bmi :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## `work type` 4 61482 15370.4 312.41 &lt; 2.2e-16 ***
## Residuals 4904 241275 49.2
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>stroke %&gt;% group_by(`work type`) %&gt;% summarize(mean(age), mean(`avg glucose level`), 
    mean(bmi))</code></pre>
<pre><code>## # A tibble: 5 x 4
## `work type` `mean(age)` `mean(\`avg glucose level\`)`
`mean(bmi)`
## &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 children 6.88 94.0 20.0
## 2 Govt_job 50.7 107.  30.5
## 3 Never_worked 16.2 96.0 25.5
## 4 Private 45.2 106.  30.3
## 5 Self-employed 59.9 112.  30.2</code></pre>
<pre class="r"><code># post-hoc t test
pairwise.t.test(stroke$bmi, stroke$`work type`, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  stroke$bmi and stroke$`work type` 
## 
##               children Govt_job Never_worked Private
## Govt_job      &lt; 2e-16  -        -            -      
## Never_worked  0.00029  0.00108  -            -      
## Private       &lt; 2e-16  0.48193  0.00153      -      
## Self-employed &lt; 2e-16  0.40976  0.00210      0.74449
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(stroke$`avg glucose level`, stroke$`work type`, 
    p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  stroke$`avg glucose level` and stroke$`work type` 
## 
##               children Govt_job Never_worked Private
## Govt_job      5.3e-08  -        -            -      
## Never_worked  0.83169  0.23739  -            -      
## Private       8.7e-10  0.38353  0.30874      -      
## Self-employed 3.5e-15  0.03363  0.08683      0.00017
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code># type 1 error
1 - 0.95^20</code></pre>
<pre><code>## [1] 0.6415141</code></pre>
<pre class="r"><code># bonferroni correction
pairwise.t.test(stroke$`avg glucose level`, stroke$`work type`, 
    p.adj = &quot;bonferroni&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  stroke$`avg glucose level` and stroke$`work type` 
## 
##               children Govt_job Never_worked Private
## Govt_job      5.3e-07  -        -            -      
## Never_worked  1.0000   1.0000   -            -      
## Private       8.7e-09  1.0000   1.0000       -      
## Self-employed 3.5e-14  0.3363   0.8683       0.0017 
## 
## P value adjustment method: bonferroni</code></pre>
<pre class="r"><code>pairwise.t.test(stroke$bmi, stroke$`work type`, p.adj = &quot;bonferroni&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  stroke$bmi and stroke$`work type` 
## 
##               children Govt_job Never_worked Private
## Govt_job      &lt;2e-16   -        -            -      
## Never_worked  0.0029   0.0108   -            -      
## Private       &lt;2e-16   1.0000   0.0153       -      
## Self-employed &lt;2e-16   1.0000   0.0210       1.0000 
## 
## P value adjustment method: bonferroni</code></pre>
<pre class="r"><code># bonferroni adjusted significance level
0.05/20</code></pre>
<pre><code>## [1] 0.0025</code></pre>
<p>Multivariate normality for each group was tested in order to test for the MANOVA assumptions, and the resulting p value &lt; 0.05 proves that the assumptions are most likely not met. A one-way MANOVA was conducted to determine the effect of work on three dependent variables of age, average glucose levels, and bmi. In doing so, significant differences were found across regions for at least one of the numeric variables, Pillai trace = 0.54294, pseudo F (12, 14712) = 270.91, p &lt; 0.001. As follow-up tests to the MANOVA, univariate ANOVAs for each of the numeric variables were conducted. The ANOVAs also showed significant results on the two dependent numeric variables. For average glucose level, it was shown that F (4, 4904) = 16.6, p &lt; 0.0001. For bmi, it was shown that F (4, 4094) = 312.41, p &lt; 0.0001. Post-hoc t tests were performed on the 2 ANOVAs in pairwise comparisons to determine which works differed in average glucose level and bmi. 1 MANOVA, 3 ANOVAs, and 16 t tests were done to result in 20 tests total. The overall type-I error rate was 0.6415141, and the bonferroni adjusted significance level of α = 0.05/20 = 0.0025 should be used to keep the overall type-I error rate at 0.05. Post-hoc analysis was performed with the bonferroni adjustment and the results showed that all of the pairs except for government job and children, never worked and government job, private and government job, and private and never worked, differed significantly in the average glucose level. All of the pairs except for private and government job, self-employed and government job, and self-employed and private, differed significantly in bmi when the bonferroni correction was used.</p>
</div>
<div id="randomization-test" class="section level3">
<h3>2 - Randomization test</h3>
<pre class="r"><code>stroke1 &lt;- stroke %&gt;% select(gender, bmi)
stroke1</code></pre>
<pre><code>## # A tibble: 4,909 x 2
##    gender   bmi
##    &lt;chr&gt;  &lt;dbl&gt;
##  1 Male    36.6
##  2 Male    32.5
##  3 Female  34.4
##  4 Female  24  
##  5 Male    29  
##  6 Male    27.4
##  7 Female  22.8
##  8 Female  24.2
##  9 Female  29.7
## 10 Female  36.8
## # … with 4,899 more rows</code></pre>
<pre class="r"><code>ggplot(stroke1, aes(bmi, fill = gender)) + geom_histogram(bins = 6.5) + 
    facet_wrap(~gender, ncol = 2) + theme(legend.position = &quot;none&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>set.seed(348)
stroke1 %&gt;% group_by(gender) %&gt;% summarize(means = mean(bmi)) %&gt;% 
    summarize(diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `diff(means)`
##           &lt;dbl&gt;
## 1        -0.416</code></pre>
<pre class="r"><code># randomization test
rand_dist &lt;- vector()
for (i in 1:5000) {
    new &lt;- data.frame(bmi = sample(stroke1$bmi), gender = stroke1$gender)
    rand_dist[i] &lt;- mean(new[new$gender == &quot;Female&quot;, ]$bmi) - 
        mean(new[new$gender == &quot;Male&quot;, ]$bmi)
}
mean(rand_dist &gt; 0.4155212 | rand_dist &lt; -0.4155212)</code></pre>
<pre><code>## [1] 0.0686</code></pre>
<pre class="r"><code>{
    hist(rand_dist, main = &quot;&quot;, ylab = &quot;&quot;)
    abline(v = c(-0.4155212, 0.4155212), col = &quot;red&quot;)
}</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-3-2.png" width="768" style="display: block; margin: auto;" />
A randomization test for the mean difference of bmi based on gender is conducted. The null hypothesis is that the mean bmi are the same for female and male patients. The alternative hypothesis is that the mean bmi are different for female and male patients. The two tailed p-value for the randomization test is p = 0.0686. Since p &gt; 0.05, it can be concluded that there is not a significance difference in mean charges between female and male patients, and we fail to reject the null hypothesis.</p>
</div>
<div id="linear-regression-model" class="section level3">
<h3>3 - Linear Regression Model</h3>
<pre class="r"><code># mean centering numeric variables
stroke$avgglucoselevel_c &lt;- (stroke$`avg glucose level` - mean(stroke$`avg glucose level`, 
    na.rm = T))
stroke$bmi_c &lt;- (stroke$bmi - mean(stroke$bmi, na.rm = T))

# linear regression
fit &lt;- lm(avgglucoselevel_c ~ bmi_c * gender, data = stroke)
summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = avgglucoselevel_c ~ bmi_c * gender, data =
stroke)
##
## Residuals:
## Min 1Q Median 3Q Max
## -122.82 -28.25 -12.54 11.22 166.59
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -2.1212 0.8114 -2.614 0.00897 **
## bmi_c 0.9387 0.1000 9.383 &lt; 2e-16 ***
## genderMale 5.2194 1.2679 4.117 3.91e-05 ***
## bmi_c:genderMale 0.1688 0.1644 1.027 0.30469
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 43.67 on 4905 degrees of
freedom
## Multiple R-squared: 0.03433, Adjusted R-squared: 0.03373
## F-statistic: 58.12 on 3 and 4905 DF, p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code># plot
ggplot(stroke, aes(x = bmi_c, y = avgglucoselevel_c, group = gender)) + 
    geom_point(aes(color = gender)) + geom_smooth(method = &quot;lm&quot;, 
    aes(color = gender))</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code># check assumptions of linearity, homoskedasticity
resids &lt;- fit$residuals
fitvals &lt;- fit$fitted.values
ggplot() + geom_point(aes(fitvals, resids)) + geom_hline(yintercept = 0, 
    color = &quot;red&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(sandwich)
library(lmtest)
bptest(fit)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 221.19, df = 3, p-value &lt; 2.2e-16</code></pre>
<pre class="r"><code># normality
ks.test(resids, &quot;pnorm&quot;, mean = 0, sd(resids))</code></pre>
<pre><code>## 
##  One-sample Kolmogorov-Smirnov test
## 
## data:  resids
## D = 0.16249, p-value &lt; 2.2e-16
## alternative hypothesis: two-sided</code></pre>
<pre class="r"><code># robust standard errors
coeftest(fit, vcov = vcovHC(fit))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -2.12122 0.77665 -2.7312 0.006332 **
## bmi_c 0.93868 0.11013 8.5232 &lt; 2.2e-16 ***
## genderMale 5.21945 1.29410 4.0333 5.584e-05 ***
## bmi_c:genderMale 0.16879 0.20565 0.8207 0.411833
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code># proportion of variation in outcome
(sum((stroke$avgglucoselevel_c - mean(stroke$avgglucoselevel_c))^2) - 
    sum(fit$residuals^2))/sum((stroke$avgglucoselevel_c - mean(stroke$avgglucoselevel_c))^2)</code></pre>
<pre><code>## [1] 0.03432553</code></pre>
<p>For female patients, for every 1 unit increase of bmi, average glucose level increases by 0.9387 (significant, t = 9.383, df = 4905, p &lt; 0.0000000000000002). When controlling for bmi, males have average glucose levels that are 5.2194 greater than females (significant, t = 4.117, df = 4905, p = 0.0000391). The slope for bmi on average glucose level is 0.1688 greater for males compared to females (interaction is not significant, t = 1.027, df = 4905, p = 0.30469). The assumptions of linearity, normality, and homoskedasticity are not met becaue p &lt; 0.05. Regression is then recomputed using the robust standard errors. When controlling for gender, there is a significant interaction between bmi and average glucose levels (t = 8.5232, p &lt; 0.00000000000000022). There are no changes in significance after the robust SEs. The model explains 0.03432553 of the variation in the outcome.</p>
</div>
<div id="bootstrapped-linear-regression-model" class="section level3">
<h3>4 - Bootstrapped Linear Regression Model</h3>
<pre class="r"><code># linear regression
fit &lt;- lm(avgglucoselevel_c ~ bmi_c * gender, data = stroke)
summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = avgglucoselevel_c ~ bmi_c * gender, data =
stroke)
##
## Residuals:
## Min 1Q Median 3Q Max
## -122.82 -28.25 -12.54 11.22 166.59
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -2.1212 0.8114 -2.614 0.00897 **
## bmi_c 0.9387 0.1000 9.383 &lt; 2e-16 ***
## genderMale 5.2194 1.2679 4.117 3.91e-05 ***
## bmi_c:genderMale 0.1688 0.1644 1.027 0.30469
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 43.67 on 4905 degrees of
freedom
## Multiple R-squared: 0.03433, Adjusted R-squared: 0.03373
## F-statistic: 58.12 on 3 and 4905 DF, p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code># bootstrapped SEs
resids &lt;- fit$residuals
fitted &lt;- fit$fitted.values
resid_resamp &lt;- replicate(5000, {
    new_resids &lt;- sample(resids, replace = TRUE)
    stroke$new_y &lt;- fitted + new_resids
    fit2 &lt;- lm(new_y ~ bmi_c * gender, data = stroke)
    coef(fit2)
})
resid_resamp %&gt;% t %&gt;% as.data.frame %&gt;% summarize_all(sd)</code></pre>
<pre><code>##   (Intercept)      bmi_c genderMale bmi_c:genderMale
## 1   0.8090762 0.09977304   1.260057        0.1661396</code></pre>
<pre class="r"><code># normal SEs
coeftest(fit)</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -2.12122 0.81136 -2.6144 0.008966 **
## bmi_c 0.93868 0.10004 9.3834 &lt; 2.2e-16 ***
## genderMale 5.21945 1.26791 4.1166 3.909e-05 ***
## bmi_c:genderMale 0.16879 0.16442 1.0265 0.304687
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code># robust SEs
coeftest(fit, vcov = vcovHC(fit))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -2.12122 0.77665 -2.7312 0.006332 **
## bmi_c 0.93868 0.11013 8.5232 &lt; 2.2e-16 ***
## genderMale 5.21945 1.29410 4.0333 5.584e-05 ***
## bmi_c:genderMale 0.16879 0.20565 0.8207 0.411833
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p>The bootstrapped SEs are 0.09977304 for bmi, 1.260057 for genderMale, and 0.1661396 for bmi:genderMale. The bmi and genderMale SEs are slightly lower than the original SEs of 0.10004 for bmi and 1.26791 for genderMale, and the bmi:genderMale is slightly greater than the original SE of 0.16442 for bmi:genderMale. The robust SEs differ slightly from the bootstrapped SEs, as the bmi SE is greater at 0.11013, the genderMale SE is greater at 1.29410, and the bmi:genderMale SE is greater at 0.20565. In the bootstrapped regression, p-values can be predicted to decrease, differing from the original p-values that are &lt; 0.0000000000000002 (significant), 0.0000391 (significant), and 0.30469 (not significant) for bmi, genderMale, and bmi:genderMale, respectively.</p>
</div>
<div id="logistic-regression-model" class="section level3">
<h3>5 - Logistic Regression Model</h3>
<pre class="r"><code># mean center age
stroke$age_c &lt;- (stroke$age - mean(stroke$age, na.rm = T))

# logistic regression
fit3 &lt;- glm(`heart disease` ~ avgglucoselevel_c + age_c, data = stroke, 
    family = binomial(link = &quot;logit&quot;))
summary(fit3)</code></pre>
<pre><code>##
## Call:
## glm(formula = `heart disease` ~ avgglucoselevel_c +
age_c, family = binomial(link = &quot;logit&quot;),
## data = stroke)
##
## Deviance Residuals:
## Min 1Q Median 3Q Max
## -1.0632 -0.3159 -0.1636 -0.0730 3.8742
##
## Coefficients:
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -4.135062 0.144897 -28.538 &lt; 2e-16 ***
## avgglucoselevel_c 0.005910 0.001156 5.114 3.16e-07 ***
## age_c 0.076313 0.005251 14.532 &lt; 2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## (Dispersion parameter for binomial family taken to be 1)
##
## Null deviance: 1934.6 on 4908 degrees of freedom
## Residual deviance: 1511.8 on 4906 degrees of freedom
## AIC: 1517.8
##
## Number of Fisher Scoring iterations: 7</code></pre>
<pre class="r"><code>exp(coef(fit3))</code></pre>
<pre><code>##       (Intercept) avgglucoselevel_c             age_c 
##        0.01600168        1.00592760        1.07930003</code></pre>
<pre class="r"><code># confusion matrix
prob &lt;- predict(fit3, type = &quot;response&quot;)
pred &lt;- ifelse(prob &gt; 0.5, 1, 0)
table(predict = as.numeric(prob &gt; 0.2), truth = stroke$`heart disease`) %&gt;% 
    addmargins()</code></pre>
<pre><code>##        truth
## predict    0    1  Sum
##     0   4454  170 4624
##     1    212   73  285
##     Sum 4666  243 4909</code></pre>
<pre class="r"><code># accuracy
(4454 + 73)/4909</code></pre>
<pre><code>## [1] 0.9221837</code></pre>
<pre class="r"><code># sensitivity (TPR)
4454/4624</code></pre>
<pre><code>## [1] 0.9632353</code></pre>
<pre class="r"><code># specificity (TNR)
73/285</code></pre>
<pre><code>## [1] 0.2561404</code></pre>
<pre class="r"><code># precision (PPV)
4454/4666</code></pre>
<pre><code>## [1] 0.9545649</code></pre>
<pre class="r"><code># density plot
stroke$logit &lt;- predict(fit3, type = &quot;link&quot;)
stroke$heartdisease1 &lt;- as.factor(stroke$`heart disease`)
stroke %&gt;% group_by(heartdisease1) %&gt;% ggplot() + geom_density(aes(logit, 
    color = heartdisease1, fill = heartdisease1))</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code># ROC curve
library(plotROC)
ROCplot &lt;- ggplot(stroke) + geom_roc(aes(d = `heart disease`, 
    m = prob), n.cuts = 0) + geom_segment(aes(x = 0, xend = 1, 
    y = 0, yend = 1), lty = 2)
ROCplot</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code># calc AUC
calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.8571652</code></pre>
<p>When controlling for center age, for every 1 increase in average glucose level, the odds of having heart disease increases by a factor of 1.0059276 (significant). Controlling for center average glucose level, for every 1 year increase in center age, the odds of having heart disease increases by a factor of 1.07930003 (significant). A confusion matrix is conducted to produce an accuracy of 0.9221837, sensitivity (TPR) of 0.9632353, specificity (TNR) of 0.2561404, and precision (PPV) of 0.9545649. The accuracy is the proportion of correctly classified cases, sensitivity the true positive rate, specificity the true negative rate, and precision the proportion of those classified with heart disease and actually have heart disease. An ROC plot is made and the AUC is calculated to be 0.8571652, which is a good AUC predicting the prevalence of heart disease from average glucose level and age.</p>
</div>
<div id="logistic-regression-model-for-all-variables" class="section level3">
<h3>6 - Logistic Regression Model for all variables</h3>
<pre class="r"><code># mean center bmi
stroke$bmi_c &lt;- (stroke$bmi - mean(stroke$bmi, na.rm = T))

# logistic regression
fit4 &lt;- glm(`heart disease` ~ avgglucoselevel_c + age_c + gender + 
    bmi_c + `smoking status` + `residence type`, data = stroke, 
    family = binomial(link = &quot;logit&quot;))
summary(fit4)</code></pre>
<pre><code>##
## Call:
## glm(formula = `heart disease` ~ avgglucoselevel_c +
age_c + gender +
## bmi_c + `smoking status` + `residence type`, family =
binomial(link = &quot;logit&quot;),
## data = stroke)
##
## Deviance Residuals:
## Min 1Q Median 3Q Max
## -1.4658 -0.3085 -0.1473 -0.0603 3.8976
##
## Coefficients:
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -4.558740 0.237296 -19.211 &lt; 2e-16 ***
## avgglucoselevel_c 0.005377 0.001212 4.436 9.18e-06 ***
## age_c 0.080813 0.005721 14.126 &lt; 2e-16 ***
## genderMale 0.779032 0.144362 5.396 6.80e-08 ***
## bmi_c 0.003689 0.011626 0.317 0.75100
## `smoking status`never smoked -0.200877 0.181980 -1.104
0.26966
## `smoking status`smokes 0.595106 0.206717 2.879 0.00399
**
## `smoking status`Unknown -0.177945 0.224107 -0.794
0.42718
## `residence type`Urban -0.108979 0.141874 -0.768 0.44241
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## (Dispersion parameter for binomial family taken to be 1)
##
## Null deviance: 1934.6 on 4908 degrees of freedom
## Residual deviance: 1460.2 on 4900 degrees of freedom
## AIC: 1478.2
##
## Number of Fisher Scoring iterations: 8</code></pre>
<pre class="r"><code>exp(coef(fit4))</code></pre>
<pre><code>## (Intercept) avgglucoselevel_c age_c
## 0.01047525 1.00539130 1.08416804
## genderMale bmi_c `smoking status`never smoked
## 2.17936119 1.00369606 0.81801288
## `smoking status`smokes `smoking status`Unknown
`residence type`Urban
## 1.81322248 0.83698843 0.89674952</code></pre>
<pre class="r"><code># in-sample classification diagnostics
prob1 &lt;- predict(fit4, data = &quot;response&quot;)
class_diag(prob1, stroke$`heart disease`)</code></pre>
<pre><code>##         acc        sens      spec ppv       auc
## 1 0.9504991 0.004115226 0.9997857 0.5 0.8723724</code></pre>
<pre class="r"><code># 10 fold CV
set.seed(1234)
k = 10
data &lt;- stroke[sample(nrow(stroke)), ]
folds &lt;- cut(seq(1:nrow(stroke)), breaks = k, labels = F)
diags &lt;- NULL
for (i in 1:k) {
    train &lt;- data[folds != i, ]
    test &lt;- data[folds == i, ]
    truth1 &lt;- test$`heart disease`
    fit5 &lt;- glm(`heart disease` ~ avgglucoselevel_c + age_c + 
        gender + bmi_c + `smoking status` + `residence type`, 
        data = train, family = &quot;binomial&quot;)
    prob2 &lt;- predict(fit5, newdata = test, type = &quot;response&quot;)
    diags &lt;- rbind(diags, class_diag(prob2, truth1))
}
summarize_all(diags, mean)</code></pre>
<pre><code>##         acc        sens      spec ppv       auc
## 1 0.9496845 0.004166667 0.9989366 NaN 0.8681974</code></pre>
<pre class="r"><code># LASSO
library(glmnet)
set.seed(1234)
y &lt;- as.matrix(stroke$`heart disease`)
preds &lt;- model.matrix(`heart disease` ~ avgglucoselevel_c + age_c + 
    gender + bmi_c + `smoking status` + `residence type`, data = stroke)[, 
    -1]
head(preds)</code></pre>
<pre><code>## avgglucoselevel_c age_c genderMale bmi_c `smoking
status`never smoked
## 1 123.3848503 24.134626 1 7.7067631 0
## 2 0.6148503 37.134626 1 3.6067631 1
## 3 65.9248503 6.134626 0 5.5067631 0
## 4 68.8148503 36.134626 0 -4.8932369 1
## 5 80.9048503 38.134626 1 0.1067631 0
## 6 -35.2151497 31.134626 1 -1.4932369 1
## `smoking status`smokes `smoking status`Unknown
`residence type`Urban
## 1 0 0 1
## 2 0 0 0
## 3 1 0 1
## 4 0 0 0
## 5 0 0 1
## 6 0 0 0</code></pre>
<pre class="r"><code>cv &lt;- cv.glmnet(preds, y, family = &quot;binomial&quot;)
lasso_fit &lt;- glmnet(preds, y, family = &quot;binomial&quot;, lambda = cv$lambda.1se)
coef(lasso_fit)</code></pre>
<pre><code>## 9 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                                        s0
## (Intercept)                  -3.591568842
## avgglucoselevel_c             0.003118513
## age_c                         0.049324057
## genderMale                    0.234201716
## bmi_c                         .          
## `smoking status`never smoked  .          
## `smoking status`smokes        .          
## `smoking status`Unknown       .          
## `residence type`Urban         .</code></pre>
<pre class="r"><code># CV with LASSO
set.seed(1234)
k = 10
data &lt;- stroke[sample(nrow(stroke)), ]
folds &lt;- cut(seq(1:nrow(stroke)), breaks = k, labels = F)
diags &lt;- NULL
for (i in 1:k) {
    train2 &lt;- data[folds != i, ]
    test2 &lt;- data[folds == i, ]
    truth2 &lt;- test2$`heart disease`
    fit6 &lt;- glm(`heart disease` ~ age_c, data = train2, family = &quot;binomial&quot;)
    prob3 &lt;- predict(fit6, newdata = test2, type = &quot;response&quot;)
    diags &lt;- rbind(diags, class_diag(prob3, truth2))
}
summarize_all(diags, mean)</code></pre>
<pre><code>##         acc sens spec ppv       auc
## 1 0.9504992    0    1 NaN 0.8476613</code></pre>
<p>A logistic regression is done to predict the prevalence of heart disease from average glucose level, age, and the response variables not used yet such as gender, bmi_c, smoking status, and residence type. There is a significant result from genderMale that if the patient is a male, the odds of having heart disease increases by a factor of 2.17936119 (significant). In-sample classifications are computed to show an accuracy of 0.9504991 which is the proportion of correctly classified cases, the sensitivity (TPR) is 0.004115226 which is the true positive rate, specificity (TNR) is 0.9997857 which is the true negative rate, PPV is NaN, and AUC is 0.8723724, which is considered good. A 10 fold CV is also conducted, and the out-of-sample classification diagnostics are found to be very similar to the in-sample classifications, showing an accuracy of 0.9504992, sensitivity of 0, specificity of 1, PPV of NaN, and an AUC of 0.8476613. LASSO is performed, and the only variables that are retained are avgglucoselevel_c, age_c, and genderMale. A 10 fold CV with LASSO is conducted to give an AUC of 0.8476613, a value that is identical to the out-of-sample diagnostics. As a result, the prevalence of heart disease can be predicted from average glucose level, age, gender, bmi, smoking status, and residence type since the AUCs of all diagnostics are good.</p>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
